### ISSUE TITLE
Sword Art Online Hollow Fragment (C2-12828-1) Latest maidump

### ISSUE THREAD

**Issue by Shinigati** [BeniYukiMai/MaiDumpTool#10]
So i have tried countless times to get my dump of Sword Art Online Hollow Fragment working with maidump v233.2z2 (latest public version) my PS Vita and game region is Europe PCSB00618 i can get it running but ONLY if mode 3 is set, otherwise it will always crash with that error before starting, apparently it works for others on mode 0 and mode 5 but not for me... i tried deleting vitamin and maidump rebuild database and nothing, i'm seriously out of ideas why this is happening on only this one game so far, i dumped a few other games like cel damage or trails of cold steel but mode 0 and mode 5 works perfectly fine on them i even tried downloading someones US/EUR dump as well but that doesn't work either.

**Comment by alpakeno** [comment]
Make sure to rename\remove ux0:plugins folder if available, then try the game again.

**Comment by Shinigati** [comment]
Yep just got told the same thing, i thought the plugins were loading from ux0:app/titleid/mai_moe/mai.surpx just renamed plugins to plugins_disabled and it works now, the problem was rincheat.
