### ISSUE TITLE
Give choices for the DLC install path

### ISSUE THREAD

**Issue by iadlast** [BeniYukiMai/MaiDumpTool#25]
It would be a good idea to let players choose between at the least app0:dlc and app0: for the DLC install path. After all, as it was exemplified with Ciel nosurge's costume DLC, if the folder sublevels are at 10 or higher, it becomes impossible to have the files for them working properly.

**Comment by iadlast** [comment]
Discovered that this issue seems to be solely a VitaShell problem. Therefore, I'll close it now.

**Comment by dateno1** [comment]
It work with mode6 but mode5 is not

also can't share DLC with other titles if it installed on app0:/dlc (example : senrankagura)
