### ISSUE TITLE
Gravity Rush PCSA00011 US Digital

### ISSUE THREAD

**Issue by alpakeno** [BeniYukiMai/MaiDumpTool#3]
It only works when changed mai loading module to 3 ( use only 2 modules that with with _m.suprx ) otherwise it always crashes...
And when I try to use mode 5 with DLC support to load the DLC it also crashes... And I cannot get the dlc to works in mode 3!

**Comment by realshotgun** [comment]
DLC isn't supposed to work in mode 3.  The only mode which it will work in is mode 5.  If mode 5 isn't working, then it won't use DLC.

**Comment by alpakeno** [comment]
Yeah I know mode 3 will not work with DLC, and this is the only mode that works with this game by using only libc_m.suprx and libfios2_m.suprx, so I hope the next version will fix the issue if there.

**Comment by alpakeno** [comment]
Problem solved after deleting, **ux0:seplugins** folder. ( rinCheat is causing that crash )
